baseURL = "https://radarstation.tk/"
languageCode = "de"
title = "Radarstation"
theme = "mainroad"

paginate = "10" # Number of posts per page
[Params]
    subtitle = "Tarnkappe.info Watchblog" # Subtitle of your site. Used in site header
    description = "Wir schauen den Autoren von Tarnkappe.info auf den Finger." # Description of your site. Used in meta description
    opengraph = false # Enable OpenGraph if true
    twitter_cards = false # Enable Twitter Cards if true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
